# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NAlZX4-oYRboHB9zxuDiCcI2cgMU79q0
"""

import nltk
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize

# Download necessary resources
nltk.download('averaged_perceptron_tagger')
nltk.download('punkt')
nltk.download('wordnet')

def get_wordnet_pos(tag):
    """
    Map POS tag to first character used by WordNetLemmatizer
    """
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

def paraphrase(text):
    """
    Paraphrase text by replacing words with their synonyms
    """
    # Tokenize text into words
    words = word_tokenize(text)
    
    # Get the part of speech for each word
    tagged_words = nltk.pos_tag(words)
    
    # Create a new list of words with synonyms substituted for some of them
    new_words = []
    for word, tag in tagged_words:
        # Map the part of speech to a WordNet POS tag
        wn_tag = get_wordnet_pos(tag)
        
        # Find synonyms for the word using WordNet
        synonyms = set()
        for syn in wordnet.synsets(word, pos=wn_tag):
            for lemma in syn.lemmas():
                synonyms.add(lemma.name())
        
        # If there are synonyms available, choose one at random to replace the word
        if synonyms:
            new_word = synonyms.pop()
            new_words.append(new_word)
        else:
            new_words.append(word)
    
    # Combine the new words into a new sentence
    new_sentence = " ".join(new_words)
    return new_sentence

text = "At the very top of the hay-mow in the barn, the Speckled Hen had made her nest, and each day for twelve days she had laid in it a pretty white egg. The Speckled Hen had made her nest in this out-of-the-way place so that no one would come to disturb her, as it was her intention to sit upon the eggs until they were hatched into chickens. Each day, as she laid her eggs, she would cackle to herself; saying, 'This will in time be a beautiful chick, with soft, fluffy down all over its body and bright little eyes that will look at the world in amazement. It will be one of my children, and I shall love it dearly.' She named each egg, as she laid it, by the name she should call it when a chick, the first one being 'Cluckety-Cluck,' and the next 'Cadaw-Cut,' and so on; and when she came to the twelfth egg she called it 'Humpty Dumpty.' This twelfth egg was remarkably big and white and of a very pretty shape, and as the nest was now so full she laid it quite near the edge. And then the Speckled Hen, after looking proudly at her work, went off to the barnyard, clucking joyfully, in search of something to eat. When she had gone, Cluckety-Cluck, who was in the middle of the nest and the oldest egg of all, called out, angrily,"
paraphrased_text = paraphrase(text)
print(paraphrased_text)